find_a_volunteer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('find_a_volunteer_dir.urls')), #what this means is ...
#... everything that comes into our website domain will redirect to the other..
#.. urls.py file.
    path('users/',include('users.urls'))
]

find_a_volunteer_dir/urls.py
from django.urls import path
from . import views

app_name="find_a_volunteer_dir" #This tells django what the application namespace...
#...these urls refer to is.

#the first parameter is the pattern being matched. The pattern is the ...
    #... bit that comes after the domain name so a '' pattern means it is matching a url which is just the domain name.
    #the second part tells it what view to call when this url pattern is requested. The third part provides a name for..
    #.. this url so we can refer to it elsewhere.
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('volunteer/homepage/', views.volunteer_homepage, name='volunteer_homepage'),
    path('organisation/homepage/', views.organisation_homepage, name='organisation_homepage'),
    path('error/', views.error_page, name="error_page"),
    path('volunteer/new_volunteer_profile/',views.new_volunteer_profile,name='new_volunteer_profile'),
    path('volunteer/view_volunteer_profile/', views.view_volunteer_profile,name='view_volunteer_profile'),
    path('volunteer/edit_volunteer_profile/',views.edit_volunteer_profile,name='edit_volunteer_profile'),
    path('volunteer/generate_matches/',views.match_volunteer_with_organisations,name='match_volunteer_with_organisations'),
    path('volunteer/accept_or_reject_matches/',views.accept_or_reject_matches,name='accept_or_reject_matches'),
    path('organisation/new_organisation_profile',views.new_organisation_profile,name='new_organisation_profile'),
    path('organisation/view_organisation_profile',views.view_organisation_profile,name='view_organisation_profile'),
    path('organisation/edit_organisation_profile',views.edit_organisation_profile,name='edit_organisation_profile'),
    path('volunteer/view_matched_organisation_profile/<int:organisation_id>/',views.view_matched_organisation_profile,
        name='view_matched_organisation_profile'),     
    #^<int:[]> is used to indicate pagination i.e where there is an index number required for the page.
    path('volunteer/view_accepted_organisations',views.view_accepted_organisations,name='view_accepted_organisations'),
    path('organisation/view_volunteers_who_have_accepted',views.view_volunteers_who_have_accepted,
        name='view_volunteers_who_have_accepted'),
    path('organisation/view_accepted_volunteer_profile/<int:volunteer_id>/',views.view_accepted_volunteer_profile,
        name='view_accepted_volunteer_profile'),
    path('verify_account/',views.verify_account,name='verify_account'),
    path('verify_account/captcha/',views.verify_account_captcha,name="verify_account_captcha"),
    path('verify_account/handwritten_digit/',views.verify_account_handwritten_digit,name="verify_account_handwritten_digit"),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
	#the 2 auth_views.[] are already defined by Django and are imported in.
    path('login/',
    	auth_views.LoginView.as_view(template_name='users/login.html'),
    	name='login'), 
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/',views.register, name='register'),
    #The views.register view is the only one I will need to define.
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# The below contains the choices for user_type.
USER_TYPE_CHOICES=(
        ("volunteer",'volunteer'),
        ("organisation",'organisation'),
        ) #the form of these choices lists is ([value],[label]),

#The model inherits from Django's AbstractUser which already has the username and password fields.
class CustomUser(AbstractUser):
    user_type=models.CharField(max_length=25, choices = USER_TYPE_CHOICES)

users/views.py
from django.shortcuts import render
from django.contrib.auth import login,logout, authenticate
from find_a_volunteer_dir.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.urls import reverse

def register(request):
#There are two types of requests: GET and POST requests.
#In a GET request, data is requested from the web host machine by the client.
#In a POST request, data is submitted by the client to the web host to be processed.

    if request.method != 'POST':
        form = UserCreationForm() 
    #^this means if the request to the web hosting machine is not giving data then we create...
    #...an instance of the form with no data.
    else: 
        #this means we are being given data so we create an instance of the form with our data.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user=form.save()
            authenticated_user=authenticate(username=new_user.username,password=request.POST['password1'])
            login(request,authenticated_user) #The login function is defined by Django, not me.
            return HttpResponseRedirect(reverse('find_a_volunteer_dir:homepage'))
            #^After being logged in, the user is redirected to the (base) homepage.
    args={'form':form} #The form is passed as an argument to the template.
    return render(request, 'users/register.html',args)

users/templates/users/login.html
<a href="{% url 'find_a_volunteer_dir:homepage' %}">Homepage</a>
<span style="font-family:Courier">	
<!--This block below determines what do if there is an error with the form.-->
<!--The errors are defined by Django in the default create user form my... -->
<!-- ... custom create user form inherits from.-->
{% if form.errors %}
	<p> Your username and password don't match, please try again. </p>
{% endif %}

<!--The method="post" part tells Django that this form is going to send data...-->
<!--... TO the web host machine. The url part tells Django which url and ...-->
<!--... corresponding view is going to process the form data / request.-->
<form method="post" action="{% url 'users:login' %}">
	{% csrf_token %} <!--The csrf_token tag is used by Django to avoid malicious attacks.-->
	{{ form.as_p }}
	<button name ="submit">log in</button>
	<input type="hidden" name="next" value="{% url 'find_a_volunteer_dir:homepage' %}" />
</form>

</span>

users/templates/users/register.html
<a href="{% url 'find_a_volunteer_dir:homepage' %}">Homepage</a>

<span style="Font-family:Courier">
<form method="post" action="{% url 'users:register' %}">
	{% csrf_token %}
	{{ form.as_p }}
	<button name="submit">register</button>
	<input type ="hidden" name="next" value="{% url 'find_a_volunteer_dir:homepage' %}" />
	<!--A "hidden" type input is an input which is passed with the user's input to the ...-->
	<!--...form and which can't be seen or modified by the user. -->
</form>
</span>