find_a_volunteer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('find_a_volunteer_dir.urls')), #what this means is ...
#... everything that comes into our website domain will redirect to the other..
#.. urls.py file.
    path('users/',include('users.urls'))
]

find_a_volunteer_dir/urls.py
from django.urls import path
from . import views

app_name="find_a_volunteer_dir" #This tells django what the application namespace...
#...these urls refer to is.

#the first parameter is the pattern being matched. The pattern is the ...
    #... bit that comes after the domain name so a '' pattern means it is matching a url which is just the domain name.
    #the second part tells it what view to call when this url pattern is requested. The third part provides a name for..
    #.. this url so we can refer to it elsewhere.
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('volunteer/homepage/', views.volunteer_homepage, name='volunteer_homepage'),
    path('organisation/homepage/', views.organisation_homepage, name='organisation_homepage'),
    path('error/', views.error_page, name="error_page"),
    path('volunteer/new_volunteer_profile/',views.new_volunteer_profile,name='new_volunteer_profile'),
    path('volunteer/view_volunteer_profile/', views.view_volunteer_profile,name='view_volunteer_profile'),
    path('volunteer/edit_volunteer_profile/',views.edit_volunteer_profile,name='edit_volunteer_profile'),
    path('volunteer/generate_matches/',views.match_volunteer_with_organisations,name='match_volunteer_with_organisations'),
    path('volunteer/accept_or_reject_matches/',views.accept_or_reject_matches,name='accept_or_reject_matches'),
    path('organisation/new_organisation_profile',views.new_organisation_profile,name='new_organisation_profile'),
    path('organisation/view_organisation_profile',views.view_organisation_profile,name='view_organisation_profile'),
    path('organisation/edit_organisation_profile',views.edit_organisation_profile,name='edit_organisation_profile'),
    path('volunteer/view_matched_organisation_profile/<int:organisation_id>/',views.view_matched_organisation_profile,
        name='view_matched_organisation_profile'),     
    #^<int:[]> is used to indicate pagination i.e where there is an index number required for the page.
    path('volunteer/view_accepted_organisations',views.view_accepted_organisations,name='view_accepted_organisations'),
    path('organisation/view_volunteers_who_have_accepted',views.view_volunteers_who_have_accepted,
        name='view_volunteers_who_have_accepted'),
    path('organisation/view_accepted_volunteer_profile/<int:volunteer_id>/',views.view_accepted_volunteer_profile,
        name='view_accepted_volunteer_profile'),
    path('verify_account/',views.verify_account,name='verify_account'),
    path('verify_account/captcha/',views.verify_account_captcha,name="verify_account_captcha"),
    path('verify_account/handwritten_digit/',views.verify_account_handwritten_digit,name="verify_account_handwritten_digit"),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
	#the 2 auth_views.[] are already defined by Django and are imported in.
    path('login/',
    	auth_views.LoginView.as_view(template_name='users/login.html'),
    	name='login'), 
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/',views.register, name='register'),
    #The views.register view is the only one I will need to define.
]

find_a_volunteer_dir/views.py
from django.shortcuts import render
#render is defined by Django and is used to "render" templates 

from .models import image_upload, volunteer_profile,organisation_profile, matched_organisations, accepted_organisations, verification_details
#These models from the models.py file which is located in the same directory as this file are used in various views to ...
#... create/edit/delete/query objects of these models.

from django.shortcuts import redirect
#many views and decorators use Django's redirect function to redirect users to other pages based on certain events.

from functools import wraps
#Wraps is a crucial part of the decorators.

from django.http import HttpResponseRedirect
#HttpResponseRedirect is a more flexible version of redirect with more or less the same purpose.

from .forms import upload_image_form, volunteer_profile_form, organisation_profile_form, accept_reject_form, captcha_verification_form
#These forms from the forms.py file located in the same directory as this file are used in various views.

from users.models import CustomUser
#Various views query objects of my CustomUser model. This model cannot be imported together with the ones in line 4 as it is located in...
#... the models.py file in the users app whereas the other models are located in the models.py file in the find_a_volunteer_dir app...
#...which is the app that this file is also inside.

import requests
#Every view takes request a parameter. The request parameter is a HttpRequest object which contains data about the request.

from .my_extra_modules import (split_string, date_time_format_converter, latest_tweet, list_contains_element, merge, 
      dictionary_to_key_value_list, merge_sort_list_of_key_value_pairs_by_value, apply_filter, transpose, concatenate_4_image_arrays, 
      letter_modification_1, letter_modification_2, letter_modification_3)
#These functions from the my_extra_modules.py are used in various views.

import random #This is used in some views


 # this is so I can pass my user to the homepage template in the homepage view.
# Create your views here.

#The function the decorator "wraps" around is a parameter to the decorator function.
#Hence making decorators HIGHER ORDER FUNCTIONS. 
def must_be_logged_in(function): 
      @wraps(function)
      def wrap(request, *args, **kwargs):            
            if request.user.is_authenticated: 
            #^request.user.is_authenticated returns True if the user is authenticated (i.e logged in)                 
                  return function(request, *args, **kwargs)
            else:
                  return HttpResponseRedirect('/error/')
      return wrap

      
def volunteers_only(function):
      @wraps(function)
      def wrap(request, *args, **kwargs):
            if request.user.is_authenticated:
                  user_type = request.user.user_type
                  #The user type has to be checked after making sure...
                  #...the user is_authenticated (logged in) or else...
                  #...an error will be thrown if the user type...
                  #...of a non-logged in user is queried.
                  if user_type == 'volunteer':
                        return function(request, *args, **kwargs)
                  else:
                        #If either [if condition] is not satisifed...
                        #...the user is redirected to the error page.
                        return HttpResponseRedirect('/error/')
            else:
                  return HttpResponseRedirect('/error/')
      return wrap


def volunteer_with_one_volunteer_profile_only(function):
      @wraps(function)
      def wrap(request, *args, **kwargs):

            if request.user.is_authenticated:
                  
                  user_type = request.user.user_type
                  if user_type == 'volunteer':
                        num_volunteer_profiles=volunteer_profile.objects.filter(owner_id=request.user.id).count()
                        #^This line gets the number of volunteer_profile objects associated with the user ...
                        #...requesting to access the view this decorator "wraps" around.
                        if num_volunteer_profiles==1:
                              return function(request, *args, **kwargs)
                        else:
                              #If any of the 3 [if conditions] are not satisifed, the user is redirected to the error page.
                              return HttpResponseRedirect('/error/')
                  else:
                        return HttpResponseRedirect('/error/')
            else:
                  return HttpResponseRedirect('/error/')

      return wrap
      

def organisations_only(function):
      @wraps(function)
      def wrap(request, *args, **kwargs):

            if request.user.is_authenticated:
                  user_type = request.user.user_type
                  if user_type == 'organisation':
                        return function(request, *args, **kwargs)
                  else:
                        return HttpResponseRedirect('/error/')
            else:
                  return HttpResponseRedirect('/error/')
      return wrap


def organisation_with_one_organisation_profile_only(function):
      @wraps(function)
      def wrap(request, *args, **kwargs):

            if request.user.is_authenticated:
                  
                  user_type = request.user.user_type
                  if user_type == 'organisation':
                        num_organisation_profiles=organisation_profile.objects.filter(owner_id=request.user.id).count()
                        if num_organisation_profiles==1:
                              return function(request, *args, **kwargs)
                        else:
                              return HttpResponseRedirect('/error/')
                  else:
                        return HttpResponseRedirect('/error/')
            else:
                  return HttpResponseRedirect('/error/')

      return wrap

#^^^^The custom decorators



def homepage(request): 

      if request.user.is_authenticated: 
      #^before filtering the verification_details objects, we have to make sure the user is_authenticated.
            if verification_details.objects.filter(owner_id=request.user.id,verified="True").count()>0:
            #The condition ^ means the user has a verification_details object where the verified field...
            #... ==True which therefore means the user is verified.      
                  verified=True 
            else:
                  verified=False
      else:                   
            verified=False
            #^If the user is not even logged in then they are not verified. 

      #The below section uses various functions (which use the twitter API with my twitter account as the PARAMETER)...
      #...from my my_extra_modules.py file.
      tweet_and_date_created=latest_tweet(1475518586663878662)
      #^This gets the latest tweet from the twitter account with that (1475...) id. This account is my...
      #...volunteering promotion twitter account.
      twitter_user = "@arun_hussain" #this is the account the id above corresponds to.
      tweet=tweet_and_date_created[0]
      #^tweet_and_date_created[0] is the actual text contents of the latest tweet from my account.

      formatted_date_created=date_time_format_converter(tweet_and_date_created[1])
      #tweet_and_date_created[1] is the date_and_time of the latest tweet and is...
      #...formatted in the way that twitter formats the information their api returns.
      #This formatting is not easily readable so I use my own formatting converter function...
      #...designed for the particular way the date_time infomation returned by the api is formatted.

      args={'tweet':tweet , 'date_created':formatted_date_created , 'twitter_user':twitter_user,'verified':verified}
      #^these are the arguments my template will need and use.
      return render(request, 'find_a_volunteer_dir/homepage.html',args)


      
def error_page(request):
      return render(request,'find_a_volunteer_dir/error_page.html')


@volunteers_only
def volunteer_homepage(request):

      #The block below is needed to get the variable necessary for me to control...
      #...when the accept-reject page link appears! Only if num_matched_remai... ...
      #... is >0 will the accept-reject link appear.  
      num_matches_remaining_to_be_decided_on=0 
      for o in matched_organisations.objects.filter(volunteer_owner_id=request.user.id):
            num_matches_remaining_to_be_decided_on+=1 
            for org in accepted_organisations.objects.filter(volunteer_owner_id=request.user.id):
                if o.id_of_matched_organisation == org.id_of_accepted_organisation:
                    num_matches_remaining_to_be_decided_on -= 1
      #The way this above code works is: For each match the volunteer user has, ...
      #... +1 is added to the variable. THEN, if that match with its particular...
      #... volunteer and organisation id also appears as an accepted_organisation...
      #... object then -1 is taken from the variable as this implies that that match...
      #... has already been decided on.


      num_accepted=accepted_organisations.objects.filter(volunteer_owner_id=request.user.id,decision="Accept").count() 
      #The num_accepted variable is needed for me to control when the view_accepted_organisations page link...
      #...appears.
                                  
      num = volunteer_profile.objects.filter(owner_id=request.user.id).count()
      #^This is number of volunteer_profiles the user has.
      num_matches=matched_organisations.objects.filter(volunteer_owner_id=request.user.id).count()
      #This is the number of matches (regardless of if they have been decided on or not)...
      #...that the user has.

      args={'num_profiles':num,'num_matches':num_matches,

find_a_volunteer_dir/templates/find_a_volunteer_dir/accept_or_reject_matches.html
<a href="{% url 'find_a_volunteer_dir:volunteer_homepage' %}">Volunteer homepage</a> 
<span style="font-family:Courier">
	
<p> Here you can accept or reject your generated matches. 
	If you choose to accept an organisation, they will be added to your list
	of accepted organisations!</p>

<!--Below, the form is displayed.-->	
<form action ="{% url 'find_a_volunteer_dir:accept_or_reject_matches' %}" method='post'>
	{% csrf_token %}
	{{ form.as_p }}
	<button name="submit">save decision</button>
</form>

</span>

find_a_volunteer_dir/templates/find_a_volunteer_dir/edit_organisation_profile.html
<a href="{% url 'find_a_volunteer_dir:organisation_homepage' %}">Organisation homepage    </a>
<span style="font-family:Courier">

<p><b>Edit your organisation's profile:</b></p>

<!--The following block presents the form and tells the template where to submit the form to.-->
<form action="{% url 'find_a_volunteer_dir:edit_organisation_profile' %}" method='post'>
	{% csrf_token %}
	{{ form.as_p }}
	<button name="submit">save changes</button>
</form>

</span>

find_a_volunteer_dir/templates/find_a_volunteer_dir/error_page.html
<a href="{% url 'find_a_volunteer_dir:homepage' %}">Homepage    </a>
<p>Sorry you don't have access to that page</p>

find_a_volunteer_dir/templates/find_a_volunteer_dir/matches_with_organisations.html
<a href="{% url 'find_a_volunteer_dir:volunteer_homepage' %}">Volunteer homepage</a>
<span style="font-family:Courier">
<p><b> Below are your matches ranked from most compatible (top of page) to least (bottom of page):</b></p>

<ul> <!--The ul tag defines a bulleted list.-->

<!--There are 2 lists being passed to this template. Both of these lists are lists of lists where
the sublists each have 2 elements. To access elements from the same index in both list,
I have to use 2 separate for loops below as well as an if statement which checks that I'm
currently at the same index in both lists. -->	
{% for pair in matches_list %}{% for other_pair in names_and_verifications_of_organisations %}
	{% if forloop.counter == forloop.parentloop.counter %} 
	<!--Each element of the list is a list with 2 elements so I need to use ".0" and ".1"-->
  		<li>Organisation name: {{ other_pair.0 }}  -  Compatibility score: {{ pair.1 }} - 
			  {{ other_pair.1 }} </li>
		<a href="{% url 'find_a_volunteer_dir:view_matched_organisation_profile' organisation_id=pair.0 %}">
			View full profile of organisation  </a>
		
	{% endif %}
{% endfor %}{% endfor %}
</ul>

</span>

find_a_volunteer_dir/templates/find_a_volunteer_dir/new_organisation_profile.html
<a href="{% url 'find_a_volunteer_dir:organisation_homepage' %}">Organisation homepage</a>
<span style="font-family:Courier">

<p><b>Fill out the details of your organisation's profile:</b></p>

<!--Below, the form passed to the template is displayed. -->
<form action ="{% url 'find_a_volunteer_dir:new_organisation_profile' %}" method='post'>
	{% csrf_token %}
	{{ form.as_p }}
	<button name="submit">save profile</button>
</form>

</span>

find_a_volunteer_dir/templates/find_a_volunteer_dir/new_volunteer_profile.html
<!--There is no need to extend the base template as the
user doesn't need to be able to logout from this page.-->
<a href="{% url 'find_a_volunteer_dir:volunteer_homepage' %}">Volunter Homepage</a>
<span style="font-family:Courier">
<p><b>Fill out the details of your volunteer profile:</b></p>

<form action ="{% url 'find_a_volunteer_dir:new_volunteer_profile' %}" method='post'>
<!--^^This tells the template which URL/page to submit the form to -->
	{% csrf_token %}
	{{ form.as_p }}
	<!--^ form.as_p is an inbuilt way of presenting the form which is 
	defined by Django. -->
	<button name="submit">save profile</button>
</form>

</span>

find_a_volunteer_dir/templates/find_a_volunteer_dir/organisation_homepage.html
{% extends "find_a_volunteer_dir/base.html" %}

{% block content %}

	<span style="font-family:Courier">

<!--The conditional statements below use variables passed by the view to the template
	to decide which links to display. -->

	{% if num_profiles == 0 %}
	<!--For example, if this condition is satisfied then the organisation does not yet
	have an organisation profile so the new_organisation_profile
	link is displayed.-->
		<p>Hi {{ user.username }}. Thanks for choosing to make an account with us.
			 Before we can open up your organisation for volunteers to potentially
			  match with, we need you to set up your organisation profile below.</p>
		<a href="{% url 'find_a_volunteer_dir:new_organisation_profile' %}">
			Create your organisation's profile</a>
	{% else %}
		<p>To view or edit your organisation's profile, use the links below.</p>
		<a href="{% url 'find_a_volunteer_dir:view_organisation_profile' %}">
			View your organisation's profile </a>
		<br>
		<a href="{% url 'find_a_volunteer_dir:edit_organisation_profile' %}">
			Edit your organisation's profile</a>
		{% if num_volunteers_who_accepted > 0 %}
			<br>
			<br>
			<a href="{% url 'find_a_volunteer_dir:view_volunteers_who_have_accepted' %}"> 
				View the volunteers who've thought that you're perfect for them</a>
				
		{% endif %}
	{% endif %}

	</span>

{% endblock content %}

find_a_volunteer_dir/templates/find_a_volunteer_dir/verify_account_captcha.html
{% extends "find_a_volunteer_dir/base.html" %}

{% block content %}

	{% load static %}
	<!-- ^ This template displays the image located at the img_src path that was passed to
this template by the view. This image is a static file so for the template to access it,
the static files have to first be loaded. The template uses the MEDIA_URL and MEDIA_ROOT settings
in settings.py to know which directory the static files are in. -->
	
	<span style="font-family:Courier">
	<a href="{% url 'find_a_volunteer_dir:homepage' %}">Homepage</a>
	<p><b>To verify yourself, please type into the box the letters you see in the image below. 
	      It is case-sensitive and don't include spaces in your answer.</b></p>

	<img src = "{% static img_src %}" >
	<!-- ^ This is how the image is actually displayed -->

	<form action ="{% url 'find_a_volunteer_dir:verify_account_captcha' %}" method='post'>
		<input type="hidden" name="hidden_verification_word" value="{{ verification_word }}" />
		<!-- The verification_word is passed as a hidden input field of the form so that
		it can be accessed in the view when the user request is a POST one. -->
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">submit</button>
	</form>
	
	</span>

{% endblock content %}

find_a_volunteer_dir/templates/find_a_volunteer_dir/view_accepted_organisations.html
<a href="{% url 'find_a_volunteer_dir:volunteer_homepage' %}">Volunteer homepage</a>
<span style="font-family:Courier">

<p><b>Here are all the organisations that you accepted. Feel free to check out their
	 location and contact details by viewing their full profile and good luck with your 
	 volunteering!</b></p>

<ul>
{% for set in name_id_compatibility_verified_list %}
	<li>Organisation name: {{ set.0 }}  -  Compatibility score: {{ set.2 }} - {{ set.3 }} </li>
	<a href="{% url 'find_a_volunteer_dir:view_matched_organisation_profile' organisation_id=set.1 %}">
		View full profile of organisation </a>
	<!--The url above is to the view_matched_organisation_profile page. The view for this page
	takes an organisation id as a parameter which is why "organisation_id=set.1" is written
	as this is the parameter this template passes to that page when the link is clicked.-->	
{% endfor %}
</ul>
</span>

find_a_volunteer_dir/templates/find_a_volunteer_dir/view_accepted_volunteer_profile.html
<a href="{% url 'find_a_volunteer_dir:volunteer_homepage' %}">Volunteer homepage</a>

<span style="font-family:Courier">

<p><b>Below are the full details of this organisation.</b></p>

<p> This organisation is {{ verified }}</p>
<p> Name: {{ organisation_profile.name }} </p>
<p> Self description: {{ organisation_profile.self_description }}</p>
<p> Contact details: {{ organisation_profile.contact_details }}</p>
<p> Postcode: {{ organisation_profile.postcode }}</p>

<p> Desired age lower bound: {{ organisation_profile.desired_age_lower_bound }}</p>
<p> Desired age upper bound: {{ organisation_profile.desired_age_upper_bound }}</p>
<p> Available volunteering activity 1: {{ organisation_profile.available_activity_1 }} </p>

{% if not organisation_profile.available_activity_2 %}
	
{% else %}
	<p> Available volunteering activity 2: {{ organisation_profile.available_activity_2 }}</p>
{% endif %}

{% if not organisation_profile.available_activity_3 %}
	
{% else %}
	<p> Available volunteering activity 3: {{ organisation_profile.available_activity_3 }}</p>
{% endif %}

<p> Monday availability: {{ organisation_profile.monday_availability }}</p>
<p> Tuesday availability: {{ organisation_profile.tuesday_availability }}</p>
<p> Wednesday availability: {{ organisation_profile.wednesday_availability }}</p>
<p> Thursday availability: {{ organisation_profile.thursday_availability }}</p>
<p> Friday availability: {{ organisation_profile.friday_availability }}</p>
<p> Saturday availability: {{ organisation_profile.saturday_availability }}</p>
<p> Sunday availability: {{ organisation_profile.sunday_availability }}</p>

</span>

find_a_volunteer_dir/templates/find_a_volunteer_dir/view_matched_organisation_profile.html
<a href="{% url 'find_a_volunteer_dir:volunteer_homepage' %}">Volunteer homepage</a>

<span style="font-family:Courier">

<p><b>Below are the full details of this organisation.</b></p>

<p> This organisation is {{ verified }}</p>
<p> Name: {{ organisation_profile.name }} </p>
<p> Self description: {{ organisation_profile.self_description }}</p>
<p> Contact details: {{ organisation_profile.contact_details }}</p>
<p> Postcode: {{ organisation_profile.postcode }}</p>

<p> Desired age lower bound: {{ organisation_profile.desired_age_lower_bound }}</p>
<p> Desired age upper bound: {{ organisation_profile.desired_age_upper_bound }}</p>
<p> Available volunteering activity 1: {{ organisation_profile.available_activity_1 }} </p>

{% if not organisation_profile.available_activity_2 %}
	
{% else %}
	<p> Available volunteering activity 2: {{ organisation_profile.available_activity_2 }}</p>
{% endif %}

{% if not organisation_profile.available_activity_3 %}
	
{% else %}
	<p> Available volunteering activity 3: {{ organisation_profile.available_activity_3 }}</p>
{% endif %}

</span>

find_a_volunteer_dir/templates/find_a_volunteer_dir/view_organisation_profile.html
<a href="{% url 'find_a_volunteer_dir:organisation_homepage' %}">Organisation homepage</a>
<!--A link to the organisation homepage is displayed at the top of the page
to allow users to easily navigate the website.-->

<span style="font-family:Courier">

<p><b> Your profile: </b></p>
<p> Name: {{ organisation_profile.name }} </p>
<p> Self description: {{ organisation_profile.self_description }}</p>
<p> Contact details: {{ organisation_profile.contact_details }}</p>
<p> Postcode: {{ organisation_profile.postcode }}</p>
<p> Desired age lower bound: {{ organisation_profile.desired_age_lower_bound }}</p>
<p> Desired age upper bound: {{ organisation_profile.desired_age_upper_bound }}</p>
<p> Available volunteering activity 1: {{ organisation_profile.available_activity_1 }} </p>

{% if not organisation_profile.available_activity_2 %}
	
{% else %}
	<p> Available volunteering activity 2: {{ organisation_profile.available_activity_2 }}</p>
{% endif %}

{% if not organisation_profile.available_activity_3 %}
	
{% else %}
	<p> Available volunteering activity 3: {{ organisation_profile.available_activity_3 }}</p>
{% endif %}

<p> Monday availability: {{ organisation_profile.monday_availability }}</p>
<p> Tuesday availability: {{ organisation_profile.tuesday_availability }}</p>
<p> Wednesday availability: {{ organisation_profile.wednesday_availability }}</p>
<p> Thursday availability: {{ organisation_profile.thursday_availability }}</p>
<p> Friday availability: {{ organisation_profile.friday_availability }}</p>
<p> Saturday availability: {{ organisation_profile.saturday_availability }}</p>
<p> Sunday availability: {{ organisation_profile.sunday_availability }}</p>

</span>

find_a_volunteer_dir/templates/find_a_volunteer_dir/view_volunteer_profile.html
<a href="{% url 'find_a_volunteer_dir:volunteer_homepage' %}">Volunteer homepage</a>
<span style="font-family:Courier">
<p><b> Your profile: </b></p>
<p> Name: {{ volunteer_profile.name }} </p>
<p> Self description: {{ volunteer_profile.self_description }}</p>
<p> Contact details: {{ volunteer_profile.contact_details }}</p>
<p> Age: {{ volunteer_profile.age }}</p>

<!--If I tried to display one of these optional fields such as
the postcode without first checking it exists then an error
would be thrown.-->
{% if not volunteer_profile.postcode %}
<!--So if the postcode field is empty, this empty branch will
just be passed through.-->	
{% else %}
	<p> Postcode: {{ volunteer_profile.postcode }}</p>
{% endif %}

<p> Most desired volunteering activity: {{ volunteer_profile.first_preferred_activity }} </p>

{% if not volunteer_profile.second_preferred_activity %}
	
{% else %}
	<p> Second most: {{ volunteer_profile.second_preferred_activity }}</p>
{% endif %}

{% if not volunteer_profile.third_preferred_activity %}
	
{% else %}
	<p> Third most: {{ volunteer_profile.third_preferred_activity }}</p>
{% endif %}

<p> Monday availability: {{ volunteer_profile.monday_availability }}</p>
<p> Tuesday availability: {{ volunteer_profile.tuesday_availability }}</p>
<p> Wednesday availability: {{ volunteer_profile.wednesday_availability }}</p>
<p> Thursday availability: {{ volunteer_profile.thursday_availability }}</p>
<p> Friday availability: {{ volunteer_profile.friday_availability }}</p>
<p> Saturday availability: {{ volunteer_profile.saturday_availability }}</p>
<p> Sunday availability: {{ volunteer_profile.sunday_availability }}</p>

</span>

find_a_volunteer_dir/templates/find_a_volunteer_dir/volunteer_homepage.html
{% extends "find_a_volunteer_dir/base.html" %}

{% block content %}
	<span style="font-family:Courier">	

	<a href="{% url 'find_a_volunteer_dir:homepage' %}">Homepage</a>

	<!--The conditional statements below use variables passed by the view to the template
	to decide which links to display. -->
	{% if num_profiles == 0 %}
		<p>Hi {{ user.username }}. Thanks for making an account with us. Before we can get 
			started in matching you with the perfect organisations for you, please fill out
			 your volunteer profile below. </p>
		<a href="{% url 'find_a_volunteer_dir:new_volunteer_profile' %}">Create your volunteer
			 profile</a>
	{% else %}
		<p>To view or edit your volunteer profile, use the links below.</p>
		<a href="{% url 'find_a_volunteer_dir:view_volunteer_profile' %}">View your profile</a>
		<a href="{% url 'find_a_volunteer_dir:edit_volunteer_profile' %}">Edit your profile</a>
		<p>If you're ready to generate your matches, follow the link below.</p>
		{% if num_matches == 0 %}
			<a href="{% url 'find_a_volunteer_dir:match_volunteer_with_organisations' %}">Generate
				 matches</a>
		{% else %}
			<a href="{% url 'find_a_volunteer_dir:match_volunteer_with_organisations' %}">Generate
				 matches again?</a>
			
			{% if num_matches_remaining_to_be_decided_on > 0 %}
				<a href="{% url 'find_a_volunteer_dir:accept_or_reject_matches' %}">Accept or reject
					 your matches</a>
			
			{% endif %}
			{% if num_accepted > 0 %}
				<a href="{% url 'find_a_volunteer_dir:view_accepted_organisations' %}">View the
					 organisations that you've accepted</a>
				
			{% endif %}
		{% endif %}
	{% endif %}
	</span>
{% endblock content %}